# Generated by Django 5.2.6 on 2025-09-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="image",
            new_name="featured_image",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="message",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
